name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install leptosfmt
        run: cargo install --locked leptosfmt

      - name: Check formatting (cargo fmt)
        run: cargo fmt --all -- --check --config group_imports=StdExternalCrate

      - name: Check formatting (leptosfmt on all workspace members)
        run: |
          leptosfmt --check .
          for member in $(cargo metadata --no-deps --format-version 1 \
            | jq -r '.packages[].manifest_path' \
            | xargs -n1 dirname \
            | sort -u); do
            echo "🔍 Running leptosfmt in $member"
            leptosfmt --check "$member"
          done

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: markdownlint
        uses: articulate/actions-markdownlint@v1

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Trunk
        run: cargo install --locked trunk

      - name: Confirm Node.js and npm are available
        run: |
          node -v
          npm -v

      - name: Install Tailwind CSS tools locally in demo/csr
        run: |
          cd demo/csr
          npm install -D tailwindcss@3 postcss autoprefixer

      - name: Make build-demo.sh executable
        run: chmod +x build-demo.sh

      - name: Run build script
        run: ./build-demo.sh

      - name: Check CSR output files
        run: |
          test -f dist/csr/index.html
          shopt -s nullglob
          wasm_files=(dist/csr/demo-csr-*_bg.wasm)
          if [ ${#wasm_files[@]} -ne 1 ]; then
            echo "❌ Expected 1 demo-csr-*_bg.wasm file, found ${#wasm_files[@]}"
            exit 1
          else
            echo "✅ Found wasm: ${wasm_files[0]}"
          fi
          js_files=(dist/csr/demo-csr-*.js)
          if [ ${#js_files[@]} -ne 1 ]; then
            echo "❌ Expected 1 demo-csr-*.js file, found ${#js_files[@]}"
            exit 1
          else
            echo "✅ Found JS: ${js_files[0]}"
          fi
          echo "CSR build artifacts found."

      - name: Check server binary exists
        run: |
          test -f target/debug/demo
          echo "Server binary found."

      - name: Run tests
        run: cargo test --workspace --all-features --verbose
